[window]
blur = true
opacity = 0.9
decorations = "full" # "full", "none", "transparent", "buttonless"

[window.padding]
x = 4
y = 2

[cursor.style]
blinking = "always"

[cursor]
blink_interval = 400
blink_timeout = 0

[mouse]
hide_when_typing = true

[font]
offset.y = 2
offset.x = 1
size = 10

[font.bold]
family = "BigBlueTermPlus Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BigBlueTermPlus Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BigBlueTermPlus Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BigBlueTermPlus Nerd Font Mono"
style = "Regular"

#[font.bold]
#family = "BigBlueTerm437 Nerd Font Mono"
#style = "Bold"
#
#[font.bold_italic]
#family = "BigBlueTerm437 Nerd Font Mono"
#style = "Bold Italic"
#
#[font.italic]
#family = "BigBlueTerm437 Nerd Font Mono"
#style = "Italic"
#
#[font.normal]
#family = "BigBlueTerm437 Nerd Font Mono"
#style = "Regular"

#[font.bold]
#family = "Fixedsys 2 Monospaced"
#style = "Bold"
#
#[font.bold_italic]
#family = "Fixedsys 2 Monospaced"
#style = "Bold Italic"
#
#[font.italic]
#family = "Fixedsys 2 Monospaced"
#style = "Italic"
#
#[font.normal]
#family = "Fixedsys 2 Monospaced"
#style = "Regular"

[colors.primary]
background = "#000000"

[general]
import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/blood_moon.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "0.9"
