#! /bin/bash

# mupdf based script for reading epubs and pdfs
#
# Running this script opens dmenu with a selection of documents 
# from the selected directory. Selecting a document opens it. 
# Upon closing the document, a second dmenu prompt will come up 
# allowing you to save your page.
#
# Usage: source books.sh [Directory where you store your books]
#
# Dependancies:
# - mupdf
# - dmenu

bookdir=$1

prompt_open="Open File:"
prompt_close="Save Page:"

page="_page"
choice="$(ls $bookdir | grep "pdf\|epub\|png" | sed "s/\..*//" | dmenu -i -p "$prompt_open")" || exit 0

# For loop is used to rediscover the file extension because
# its stripped to make the dmenu output look nicer.
for extension in "pdf" "epub" "png"; do
  book_file="$bookdir$choice.$extension"
  if [ -f $book_file ]; then
    page_file="$bookdir.$choice$page"
    if [ -f $page_file ]; then
      mupdf $book_file $(cat $page_file)
    else
      mupdf $book_file
    fi
    echo $(dmenu -p "$prompt_close" < /dev/null || cat $page_file) > $page_file
    exit 0
  fi
done;
