[window]
blur = true
opacity = 0.9
decorations = "full"

[window.padding]
x = 4
y = 2

[cursor.style]
blinking = "always"

[cursor]
blink_interval = 400
blink_timeout = 0

[mouse]
hide_when_typing = true

[font]
offset.y = 2
offset.x = 1
size = 10.5

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[colors.primary]
background = "#000000"

[general]
import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/blood_moon.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "0.9"
